# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dell\Desktop\TextEditor\text_editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 605)
        MainWindow.setMinimumSize(QtCore.QSize(805, 605))
        MainWindow.setMaximumSize(QtCore.QSize(805, 605))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\dell\\Desktop\\TextEditor\\icon/editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 0, 761, 561))
        self.textEdit.setMinimumSize(QtCore.QSize(761, 561))
        self.textEdit.setMaximumSize(QtCore.QSize(761, 561))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setTabStopWidth(20)
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 41, 561))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 26))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.act_new = QtWidgets.QAction(MainWindow)
        self.act_new.setObjectName("act_new")
        self.act_open = QtWidgets.QAction(MainWindow)
        self.act_open.setObjectName("act_open")
        self.act_saveAs = QtWidgets.QAction(MainWindow)
        self.act_saveAs.setObjectName("act_saveAs")
        self.act_save = QtWidgets.QAction(MainWindow)
        self.act_save.setObjectName("act_save")
        self.act_cut = QtWidgets.QAction(MainWindow)
        self.act_cut.setObjectName("act_cut")
        self.act_undo = QtWidgets.QAction(MainWindow)
        self.act_undo.setObjectName("act_undo")
        self.act_copy = QtWidgets.QAction(MainWindow)
        self.act_copy.setObjectName("act_copy")
        self.act_paste = QtWidgets.QAction(MainWindow)
        self.act_paste.setObjectName("act_paste")
        self.actionC = QtWidgets.QAction(MainWindow)
        self.actionC.setObjectName("actionC")
        self.act_undo_ = QtWidgets.QAction(MainWindow)
        self.act_undo_.setObjectName("act_undo_")
        self.menu_file.addAction(self.act_new)
        self.menu_file.addAction(self.act_open)
        self.menu_file.addAction(self.act_saveAs)
        self.menu_file.addAction(self.act_save)
        self.menu_edit.addAction(self.act_undo_)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.act_cut)
        self.menu_edit.addAction(self.act_copy)
        self.menu_edit.addAction(self.act_paste)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun-ExtB\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:16pt;\"><br /></p></body></html>"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_edit.setTitle(_translate("MainWindow", "编辑"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.act_new.setText(_translate("MainWindow", "新建"))
        self.act_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.act_open.setText(_translate("MainWindow", "打开..."))
        self.act_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.act_saveAs.setText(_translate("MainWindow", "另存为"))
        self.act_saveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.act_save.setText(_translate("MainWindow", "保存"))
        self.act_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.act_cut.setText(_translate("MainWindow", "剪切"))
        self.act_cut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.act_undo.setText(_translate("MainWindow", "撤销"))
        self.act_undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.act_copy.setText(_translate("MainWindow", "复制"))
        self.act_copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.act_paste.setText(_translate("MainWindow", "粘贴"))
        self.act_paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionC.setText(_translate("MainWindow", "添加新词"))
        self.act_undo_.setText(_translate("MainWindow", "撤销"))
        self.act_undo_.setShortcut(_translate("MainWindow", "Ctrl+Z"))
